### ISSUE TITLE
how can i get tf-idf file from raw FEVER dataset

### ISSUE THREAD

**Issue by Jahao26** [phoenixsecularbird/IMCI#1]
I am interested in your tfidf-Doc-Ranker in tf_idf_retrieval.py, but i dont know how to make fever-tf-idf file after reading your source code and  IMCI.

**Comment by phoenixsecularbird** [comment]
Hi! Thank you for your attention! We adopt the fever-tf-idf file from the [official baseline ](https://github.com/sheffieldnlp/naacl2018-fever/blob/master/scripts/download-processed-wiki.sh). To make the file from the raw text, please refer to [here](https://github.com/sheffieldnlp/naacl2018-fever/blob/master/src/scripts/build_tfidf.py).
